### ISSUE TITLE
Init

### ISSUE THREAD

**Issue by brettshumaker** [brettshumaker/Staff-List-Plugin#12]
- [ ] load class(es)
- [x] update plugin header
- [x] include all scripts/styles
- [ ] add admin pages
- [x] load text domain
- [x] activation/deactivation hooks

**Comment by josiahgoff** [comment]
@brettshumaker Do we need to include this in v1.2? https://github.com/brettshumaker/Staff-List-Plugin/blob/master/_inc/admin-install-uninstall.php#L205

**Comment by brettshumaker** [comment]
I don't think so. I had some issues with setting my defaults initially, but I don't think anyone is still using that old of a version.

**Comment by josiahgoff** [comment]
:+1:

**Comment by josiahgoff** [comment]
Also, with the two todos left (load classes and admin pages), what specifically do those mean? Is there anything else I need to load that isn't covered by the initial boilerplate or the other issues we created for the other pages?

**Comment by josiahgoff** [comment]
Closed by #19
