### ISSUE TITLE
Unexpected output during activation

### ISSUE THREAD

**Issue by josiahgoff** [brettshumaker/Staff-List-Plugin#22]
After copying over the activation code into the new structure, it now outputs the following error when activating:

```The plugin generated 458 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.```

<img width="1279" alt="screen shot 2015-10-19 at 5 52 12 pm" src="https://cloud.githubusercontent.com/assets/684774/10593551/67070a2c-768a-11e5-81bc-3a663cca60e6.png">

**Comment by brettshumaker** [comment]
This is coming from the activator class. Haven't tracked down exactly why yet.
