### ISSUE TITLE
Notice:Undefined variable: style_output

### ISSUE THREAD

**Issue by matt-pleth** [brettshumaker/Staff-List-Plugin#3]
I'm getting a few undefined variables when I enable debug mode on WordPress. For what it's worth, I'm using the latest version of WordPress at this moment, 3.7.1, which isn't yet supported. However, I thought this would be useful all the same.

```
Notice: Undefined variable: style_output in /httpdocs/wp-content/plugins/simple-staff-list/_inc/user-view-show-staff-list.php on line 133
Notice: Undefined variable: output in /httpdocs/wp-content/plugins/simple-staff-list/_inc/admin-views.php on line 295
```

**Comment by brettshumaker** [comment]
Thanks! I know this was forever ago, but I've fixed these issues.

**Comment by asacolips** [comment]
I've used this plugin on a few projects since the original issue went up, so that's good to hear. Thanks!
