### ISSUE TITLE
Multiple Stuff in a row

### ISSUE THREAD

**Issue by metalargie** [brettshumaker/Staff-List-Plugin#59]
Hi please see this page http://timingforum.org/about/members/
for some reason i cannot get the number of people in each row to be equal..below is the code i am using...any help?

/\* div wrapped around entire staff list _/
div.staff-member-listing {
}
/_ div wrapped around each staff member _/
div.staff-member {
width: 20%;
height: 20%;
overflow: hidden;
float: left;
margin: 5% 5%;
border: 0% solid #6c6c6c;
border-radius: 1%;
position: relative;
padding-bottom: 1em;
%border-bottom: thin dotted #aaa;
}
/_ "Even" staff member _/
div.staff-member.even {
}
/_ "Odd" staff member _/
div.staff-member.odd {
margin-top: 2em;
}
/_ Last staff member _/
div.staff-member.last {
padding-bottom: 0;
border: none;
}
/_ Wrap around staff info _/
.staff-member-info-wrap {
float: left;
width: 100%;
margin-left: 3%;
}
/_ [staff-bio-formatted] _/
div.staff-member-bio {
}
/_ p tags within [staff-bio-formatted] _/
div.staff-member-bio p {
}
/_ [staff-photo] _/
img.staff-member-photo {
float: left;
}
/_ [staff-email-link] _/
.staff-member-email {
font-size: 11px;
}
/_ [staff-name-formatted] _/
div.staff-member-listing h3.staff-member-name {
margin: 0;
font-size: 20px;
}
/_ [staff-position-formatted] _/
div.staff-member-listing h4.staff-member-position {
margin: 0;
font-size: 12px;
font-style: italic;
}
/_ Clearfix for div.staff-member _/
div.staff-member:after {
content: "";
display: block;
clear: both;
}
/_ Clearfix for <= IE7 */
- html div.staff-member { height: 1%; }
  div.staff-member { display: block; }

**Comment by brettshumaker** [comment]
@metalargie Sorry this is late - did you get this sorted out? I see you have two staff members in the same row at the link you posted.
