### ISSUE TITLE
Not Displaying Order

### ISSUE THREAD

**Issue by watrall** [brettshumaker/Staff-List-Plugin#68]
WP 4.7.2 w/ most recent version of the plugin.  Doesn't display order set in the Order section of the plugin options.  Instead, the order seems to be the most recent edited appearing at the top of the list.  Tried ASC and DESC in the shortcode, but doesn't seem to have any impact.

**Comment by dtw** [comment]
Was this fixed? I also have this issue in version 2.2.0 of SSLP but it's not a new issue.

The order on the page doesn't reflect the order in the Order tab
