### ISSUE TITLE
suggestion: display a staff member block without the entire group

### ISSUE THREAD

**Issue by ndebard** [brettshumaker/Staff-List-Plugin#72]
Say you've got a staff member, Joe Smith, and you like the way his entry displays in the staff_loop.  I'd like to be able to display just joe's block such as somehow using his staff-name-slug.  It seems it could be done by adding another template near the [staff_loop] template such as:

[staff]
<img class="staff-member-photo" src="[staff-photo-url]" alt="[staff-name] : [staff-position]">
			<div class="staff-member-info-wrap">
				<a href="[staff-name-slug]">[staff-name-formatted]</a>
				[staff-position-formatted]
				[staff-bio-formatted]
				[staff-email-link]
			</div>
[/staff]

just not in a loop over all.

**Comment by brettshumaker** [comment]
I'm getting some ideas together around templating and how I want to make multiple templates available. I'll also be adding an `id` argument to the shortcode to allow you to specify a staff member ID to just show one person's info.

**Comment by brettshumaker** [comment]
`id` argument added to shortcode in 622b1d1506fe58681e66eddd076a1e88fbe87b04 - added to v2.2.0
