### ISSUE TITLE
Can't use export

### ISSUE THREAD

**Issue by aedelgod** [brettshumaker/Staff-List-Plugin#81]
Hello @brettshumaker 

Was trying to export using the built in export tool you have for the plugin that is suppose to export it as CSV. When I click the export button the ajax wheel just turns and will continue for hours without an actual export. Browser console debug shows:
`the server responded with a status of 500 (Internal Server Error)` for admin-ajax.php
This action happens as soon as I hit the button.

WP_DEBUG Trace Stack:
`[11-Apr-2018 22:17:13 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function request_filesystem_credentials(), 0 passed in /home/[redacted]/public_html/[redacted]/wp-content/plugins/simple-staff-list/admin/class-simple-staff-list-admin.php on line 722 and at least 1 expected in /home/[redacted]/public_html/[redacted]/wp-admin/includes/file.php:1543
Stack trace:
#0 /home/[redacted]/public_html/[redacted]/wp-content/plugins/simple-staff-list/admin/class-simple-staff-list-admin.php(722): request_filesystem_credentials()
#1 /home/[redacted]/public_html/[redacted]/wp-includes/class-wp-hook.php(286): Simple_Staff_List_Admin->staff_member_export('')
#2 /home/[redacted]/public_html/[redacted]/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /home/[redacted]/public_html/[redacted]/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /home/[redacted]/public_html/[redacted]/wp-admin/admin-ajax.php(97): do_action('wp_ajax_staff_m...')
#5 {main}
  thrown in /home/[redacted]/public_html/[redacted]/wp-admin/includes/file.php on line 1543`

The server is running PHP 7.1 and the latest version of WordPress and Simple Staff List.

Thanks!

**Comment by brettshumaker** [comment]
Hey @aedelgod -
Thanks for that report. Verified the issue and will fix in next release.

If you're comfortable editing the `class-simple-staff-list-admin.php` file, change line 722 to this:
```
$url = wp_nonce_url( 'edit.php?post_type=staff-member&page=staff-member-export', 'sslp-staff-export' );
$creds = request_filesystem_credentials( $url, '', false, false, null );
```
